import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard, registerMainMenuItem } from "../toolkit/index.js";
import { booking, cancel, dateFor, guestBookings, readableDate, slots } from "../reservations.js";
registerMainMenuItem({ label: "My bookings", data: "booking:mine", order: 20 });
const composer = new Composer<Ctx>();
function menu(ctx: Ctx) { return inlineKeyboard([...guestBookings(ctx).map((b) => [inlineButton(`${readableDate(b.booking_date)} · ${b.booking_time}`, `booking:view:${b.id}`)]), [inlineButton("Back", "menu:main")]]); }
composer.callbackQuery("booking:mine", async (ctx) => { await ctx.answerCallbackQuery(); const list = guestBookings(ctx); if (!list.length) { await ctx.editMessageText("No bookings yet — tap Book a table to make one.", { reply_markup: inlineKeyboard([[inlineButton("Book a table", "booking:start")], [inlineButton("Back", "menu:main")]]) }); return; } await ctx.editMessageText("Here are your upcoming bookings.", { reply_markup: menu(ctx) }); });
composer.callbackQuery(/^booking:view:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const item = booking(ctx, ctx.match[1]); if (!item || item.guestId !== ctx.from?.id || item.status !== "confirmed") { await ctx.editMessageText("That booking is no longer active."); return; } await ctx.editMessageText(`You’re booked for ${item.party_size} at ${item.booking_time} on ${readableDate(item.booking_date)}. Your code is ${item.reference_code}.`, { reply_markup: inlineKeyboard([[inlineButton("Reschedule", `booking:reschedule:${item.id}`), inlineButton("Cancel", `booking:cancel:${item.id}`)], [inlineButton("Back", "booking:mine")]]) }); });
composer.callbackQuery(/^booking:cancel:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const item = booking(ctx, ctx.match[1]); if (!item || item.guestId !== ctx.from?.id || item.status !== "confirmed") { await ctx.editMessageText("That booking is no longer active."); return; } await ctx.editMessageText("Cancel this booking? The table will become available again.", { reply_markup: inlineKeyboard([[inlineButton("Cancel booking", `booking:cancel:yes:${item.id}`), inlineButton("Keep booking", `booking:view:${item.id}`)]]) }); });
composer.callbackQuery(/^booking:cancel:yes:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!cancel(ctx, ctx.match[1])) { await ctx.editMessageText("That booking is no longer active."); return; } await ctx.editMessageText("Your booking is cancelled. The table is available again.", { reply_markup: inlineKeyboard([[inlineButton("Book a table", "booking:start")], [inlineButton("Back", "menu:main")]]) }); });
composer.callbackQuery(/^booking:reschedule:(\d+)$/, async (ctx) => { await ctx.answerCallbackQuery(); const item = booking(ctx, ctx.match[1]); if (!item || item.guestId !== ctx.from?.id || item.status !== "confirmed") { await ctx.editMessageText("That booking is no longer active."); return; } await ctx.editMessageText("Pick a new day for this booking.", { reply_markup: inlineKeyboard([[inlineButton("Today", `booking:move-date:${item.id}:today`), inlineButton("Tomorrow", `booking:move-date:${item.id}:tomorrow`)], [inlineButton("Back", `booking:view:${item.id}`)]]) }); });
composer.callbackQuery(/^booking:move-date:(\d+):(today|tomorrow)$/, async (ctx) => { await ctx.answerCallbackQuery(); const item = booking(ctx, ctx.match[1]); if (!item || item.guestId !== ctx.from?.id || item.status !== "confirmed") { await ctx.editMessageText("That booking is no longer active."); return; } const date = dateFor(ctx.match[2] as "today" | "tomorrow"); await ctx.editMessageText("Choose a new time.", { reply_markup: inlineKeyboard([...slots(ctx, date, item.party_size).map((time) => [inlineButton(time, `booking:move-time:${item.id}:${date}:${time}`)]), [inlineButton("Back", `booking:view:${item.id}`)]]) }); });
composer.callbackQuery(/^booking:move-time:(\d+):(\d{4}-\d\d-\d\d):(\d\d:\d\d)$/, async (ctx) => { await ctx.answerCallbackQuery(); const item = booking(ctx, ctx.match[1]); if (!item || item.guestId !== ctx.from?.id || item.status !== "confirmed") { await ctx.editMessageText("That booking is no longer active."); return; } const allowed = slots(ctx, ctx.match[2], item.party_size); if (!allowed.includes(ctx.match[3])) { await ctx.editMessageText("That time was just taken. Choose another one."); return; } item.booking_date = ctx.match[2]; item.booking_time = ctx.match[3]; await ctx.editMessageText(`Your booking is moved to ${item.booking_time} on ${readableDate(item.booking_date)}.`, { reply_markup: inlineKeyboard([[inlineButton("View booking", `booking:view:${item.id}`)], [inlineButton("Back", "menu:main")]]) }); });
export default composer;
